name: "Fanart"
guid: "170a157f-ac6c-437a-abdd-ca9c25cebd39"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-fanart.png"
version: 15
targetAbi: "12.0.0.0"
framework: "net10.0"
overview: "Scrape poster images from Fanart"
description: "Scrape poster images for movies, shows, and artists in your library."
category: "MoviesAndShows"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.Fanart.dll"
changelog: |-
  - Unstable: Update to latest Jellyfin preview packages (#78) @crobibero, @enter-a-random-username, @jellyfin-bot
  - Use preview  image for faster loading times (#81) @enter-a-random-username, @crobibero
